---
version: 3

images:
  base_image:
    name: quay.io/fedora/fedora-minimal:latest

additional_build_files:
  - dest: configs
    src: ../ansible.cfg

dependencies:
  python_interpreter:
    package_system: python3
    python_path: /usr/bin/python3
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
    - openssh-clients [platform:rpm]
    - sshpass [platform:rpm]
  python:
    - kubernetes >= 12.0.0
  galaxy:
    collections:
      - name: ansible.controller
      - name: ansible.posix
      - name: awx.awx
      - name: community.general
      - name: community.okd
      - name: containers.podman
      - name: fedora.linux_system_roles
      - name: freeipa.ansible_freeipa
      - name: kubernetes.core
      - name: redhat.openshift
      - name: redhat.rhel_idm
      - name: redhat.rhel_system_roles
      - name: redhat.satellite
      - name: theforeman.foreman
    roles: []

additional_build_steps:
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN
  append_final:
    - LABEL quay.expires-after="45d"
