---
collections:
  - name: ansible.controller
  - name: ansible.posix
  - name: awx.awx
  - name: community.general
  - name: community.okd
  - name: containers.podman
  - name: fedora.linux_system_roles
  - name: freeipa.ansible_freeipa
  - name: kubernetes.core
  - name: redhat.openshift
  - name: redhat.rhel_idm
  - name: redhat.rhel_system_roles
  - name: redhat.satellite
  - name: theforeman.foreman

roles: []
