---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:2.15

additional_build_files:
  - dest: configs
    src: ../ansible.cfg

dependencies:
  system:
    - unzip [platform:rpm]
  galaxy:
    collections:
      - name: amazon.aws
      - name: community.aws
      - name: community.general
    roles: []

additional_build_steps:
  prepend_base:
    - RUN pip3 install --upgrade pip setuptools
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN
  append_final:
    # yamllint disable-line rule:line-length
    - RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/awscliv2.zip" &&
          unzip /awscliv2.zip -d /aws-install &&
          /aws-install/aws/install &&
          rm -rf /aws-install /awscliv2.zip
    - LABEL quay.expires-after="45d"

options:
  package_manager_path: /usr/bin/microdnf
