---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: >-
    'registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.14'

ansible_config: '../ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
  # yamllint disable rule:line-length
  append: |
    RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/awscliv2.zip" && \
        unzip /awscliv2.zip -d /aws-installer && \
        /aws-installer/aws/install && \
        rm -rf /aws-installer /awscliv2.zip
    LABEL quay.expires-after="45d"
